language: cpp
compiler:
  - gcc
  - clang
before_script:
  - cd ./Benchmarks
  - unzip ./IWLS_GP_r1511.zip
  - unzip ./IWLS05.zip
  - cd ..
  - sudo apt-get install libopencv-dev
  - mkdir itlPlace-build
  - cd ./itlPlace-build
  - cmake -DPETSC_DIR=../itlPlace/3rdparty/PETSc/ -DPETSC_ARCH=ubuntu-64 -DTAO_DIR=../itlPlace/3rdparty/TAO ../itlPlace/
script: (make -j5 && python ../TestingFramework/AcceptanceTest/RegressionTest.py)
notifications:
  email: false
