language: cpp
compiler:
  - gcc
  - clang
before_script:
  - tar xzfC Benchmarks/IWLS_GP_r1511.zip ./Benchmarks
  - tar xzfC Benchmarks/IWLS05.zip ./Benchmarks
  - sudo apt-get install libopencv-dev
  - mkdir itlPlace-build
  - cd ./itlPlace-build
  - cmake -DPETSC_DIR=../itlPlace/3rdparty/PETSc/ -DPETSC_ARCH=ubuntu-64 -DTAO_DIR=../itlPlace/3rdparty/TAO ../itlPlace/
script: (make -j5 && cd ../TestingFramework && python ./Run_NightExperiment_fast.py)
notifications:
  email: false
